# Generated by Django 4.0.6 on 2022-09-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Envios',
            new_name='Envio',
        ),
    ]
